Fix

diff --git a/setup_classes/cs233 b/setup_classes/cs233
--- a/setup_classes/cs233
+++ b/setup_classes/cs233
@@ -15,13 +15,13 @@ for i in $PKGS; do
 	FILE="$i-$ARCH.pkg.tar.xz"
 	wget "$URL/$FILE" >/dev/null 2>&1
 	if [ "$?" -ne "0" ]; then
-		echo "Failed to get $i." >&2
+		echo "Failed to retrieve: $i" >&2
 		rm -rf "$TMP"
 		exit 1
 	fi
 	pacman -U "$FILE" >/dev/null 2>&1
 	if [ "$?" -ne "0" ]; then
-		echo "Failed to install $i." >&2
+		echo "Failed to install: $i" >&2
 		rm -rf "$TMP"
 		exit 1
 	fi
