Added SVN Error messages

diff --git a/base/zshrc b/base/zshrc
--- a/base/zshrc
+++ b/base/zshrc
@@ -85,7 +85,17 @@ fi
 cat $HOME/.subversion/servers | grep -v "store-plaintext-passwords" > $HOME/.subversion/servers
 echo "store-plaintext-passwords = yes" >> $HOME/.subversion/servers
 echo "Downloading your CS 225 subversion folder..."
-svn co --username "$NETID" --password "$PASS" "https://subversion.ews.illinois.edu/svn/${SEM}${YEAR}-cs225/${NETID}" "$HOME/svn/cs225" >/dev/null 2>&1
+RES="$(svn co --username "$NETID" --password "$PASS" "https://subversion.ews.illinois.edu/svn/${SEM}${YEAR}-cs225/${NETID}" "$HOME/svn/cs225" </dev/null 2>&1)"
+RET="$?"
+if [ "$RET" != "0" ]; then
+	if [ "$(echo "$RES" | grep "authorization failed")" != "" ]; then
+		echo "Invalid Username or Password!"
+	elif [ "$(echo "$RES" | grep "Could not resolve hostname")" != "" ]; then
+		echo "Could not connect to EWS, Try Again? (Y/n)"
+	else
+		echo "An unknown SVN error has occurred!"
+	fi
+fi
 echo "Checked out the subversion folder for ${NETID} into ~/svn/cs225"
 
 #SETUP SSH
@@ -99,7 +109,20 @@ echo -n "Would you like to add ssh keys to EWS for easy access from this vm? (y/
 read KEYS
 if [[ "$KEYS" = "y" || "$KEYS" = "Y" ]]; then
 	sshpass -p "$PASS" ssh -o StrictHostKeyChecking=no "${NETID}@remlnx.ews.illinois.edu" "if [ ! -d ~/.ssh ]; then mkdir ~/.ssh; fi; echo \"$(cat ~/.ssh/id_rsa.pub)\" >> ~/.ssh/authorized_keys;"
+	if [ "$?" = "0" ]; then
+		echo "Added SSH Keys Successfully"
+		echo "Type the command \`ews\` to access an ews ssh session"
+	else
+		echo "Failed to set public key, Try Again? (Y/n)"
+		read TRY
+		if [[ "$TRY" != "n" && "$TRY" != "N" ]]; then
+			goto 
+		fi
+	fi
 fi
 
 #CREATE NETID FILE
 echo $NETID > ~/.netid
+
+#DISPOSE OF PASSWORD
+unset PASS
